# Initial list created on 1/16/21

spice_list = {
    'spices' : ['Dried Mint', 'Thyme', 'Curry Powder', 'Mexican Oregano',
                'Garam Masala', '21 season salute', 'Sumac', 'Rosemary',
                'Dried Dill', 'No-salt Seasoning', 'Bay Leaves', 'Nutmeg',
                'Chili Lime', 'Cloves', 'Umami Mush. Seasoning', 'Celery Salt', 
                'Sesame Seed', 'Lemon Pepper', 'Cinnamon', 'Saffron',
                'Pumpkin Spice', 'Vanilla', 'Taco Seasoning', 'Black Pepper (Ground)',
                'Black Peppercorn', 'Dill Seed', 'Everything Bagel', 'Coriander Powder',
                'Black Salt', 'Mustard Powder', 'Ginger Powder','Red Dye', 'Shan Spices'
                ],
    'oils_vinegar_syrups_liquids' : ['Mustard Oil',
                                     'Sesame Oil',
                                     'Rice Vinegar',
                                     'Mirin',
                                     'Apple Cider Vinegar',
                                     'Soy Sauce',
                                     'Vanilla Syrup'],
    'other' : ['Brown Sugar',
               'Baking Powder',
               'Irish Oats',
               'Dried Shitakes',
               'Honey',
               'Tom Yum Base',
               'Cookies',
               'Green Lentils',
               'Yeast',
               'Caramel Syrup',
               'Sugar',
               'Stevia'],
}