# Initial list created on 1/16/21

spice_list = {
    'spices' : [{'list-name' : 'Dried Mint'}, 
                {'list-name' : 'Thyme'},
                {'list-name' : 'Curry Powder'} ,
                {'list-name' : 'Mexican Oregano'} ,
                {'list-name' : 'Garam Masala'} ,
                {'list-name' : '21 season salute'} ,
                {'list-name' : 'Sumac'} ,
                {'list-name' : 'Rosemary'} ,
                {'list-name' : 'Dried Dill'} ,
                {'list-name' : 'No-salt Seasoning'} ,
                {'list-name' : 'Bay Leaves'} ,
                {'list-name' : 'Nutmeg'} ,
                {'list-name' : 'Chili Lime'} ,
                {'list-name' : 'Cloves'} ,
                {'list-name' : 'Umami Mush. Seasoning'} ,
                {'list-name' : 'Celery Salt'} ,
                {'list-name' : 'Sesame Seed'} ,
                {'list-name' : 'Lemon Pepper'} ,
                {'list-name' : 'Cinnamon'} ,
                {'list-name' : 'Saffron'} ,
                {'list-name' : 'Pumpkin Spice'} ,
                {'list-name' : 'Vanilla'} ,
                {'list-name' : 'Taco Seasoning'} ,
                {'list-name' : 'Black Pepper (Ground)'} ,
                {'list-name' : 'Black Peppercorn'} ,
                {'list-name' : 'Dill Seed'} ,
                {'list-name' : 'Everything Bagel'} ,
                {'list-name' : 'Coriander Powder'} ,
                {'list-name' : 'Black Salt'} ,
                {'list-name' : 'Mustard Powder'} ,
                {'list-name' : 'Ginger Powder'} ,
                {'list-name' : 'Red Dye'} ,
                {'list-name' : 'Shan Spices'}
                ],
    'oils_vinegar_syrups_liquids' : [{'list-name' : 'Mustard Oil'},
                                     {'list-name' : 'Sesame Oil'},
                                     {'list-name' : 'Rice Vinegar'},
                                     {'list-name' : 'Mirin'},
                                     {'list-name' : 'Apple Cider Vinegar'},
                                     {'list-name' : 'Soy Sauce'},
                                     {'list-name' : 'Vanilla Syrup'}],
    'other' : [{'list-name' : 'Brown Sugar'},
               {'list-name' : 'Baking Powder'},
               {'list-name' : 'Irish Oats'},
               {'list-name' : 'Dried Shitakes'},
               {'list-name' : 'Honey'},
               {'list-name' : 'Tom Yum Base'},
               {'list-name' : 'Cookies'},
               {'list-name' : 'Green Lentils'},
               {'list-name' : 'Yeast'},
               {'list-name' : 'Caramel Syrup'},
               {'list-name' : 'Sugar'},
               {'list-name' : 'Stevia'}],
}